#!/bin/sh
#/etc/init.d/pyboot
### BEGIN INIT INFO
# Provides:pyboot
# Required-Start:$remote_fs $syslog
# Required-Stop:$remote_fs $syslog
# Default-Start:2 3 4 5
# Default-Stop:0 1 6
# Short-Description: pyboot
# Description: This service is used to start my applaction
### END INIT INFO

case "$1" in
     start)
     echo "start your app here."
     su pi -c "exec /home/pi/AI_shequ/pyboot.sh"
     ;;
     stop)
     echo "stop your app here."
     ;;
     *)
     echo "Usage: service testboot start|stop"
     exit 1
     ;;
esac
exit 0
